// Package audit holds the persistence entity for the HLD-010 audit trail.
// One row per (actor, action, resource, outcome) observation. The whole
// point of this table is to be unforgeable record-keeping for "who did
// what" — code in this package must never mutate or delete rows except via
// the retention job.
//
// The action vocabulary that used to be spelled out here now lives in
// core/base/pkg/audit and is re-exported below, so a handler in
// another bounded context can name a row without importing this package
// (decision 109). The GORM entities stayed: they are storage, not
// vocabulary, and nothing outside data/audit/store has any business
// knowing that this table is called audit_logs.
package audit

import (
	"time"

	auditport "github.com/vincent-wuhan/opskeeper/core/base/pkg/audit"
)

// Log is one audit observation.
//
// Field-level notes:
//
//   - UserID is *uint64 so the unauthenticated-actor path (failed login,
//     anon endpoint) can write NULL and still satisfy the FK semantics
//     a future migration may add.
//   - All TEXT columns are NOT NULL but **without** a GORM-level
//     default:” tag — MySQL 8 rejects DEFAULT on TEXT (Error 1101), as
//     tripped by v0.7.43's investigation_report migration. Go's zero
//     value for string is "" so NOT NULL is satisfied at insert time.
//   - PayloadJSON is the only free-form field. The biz layer must
//     redact secrets BEFORE serialising (LLM keys, SSH keys, passwords,
//     tokens). What lives here is the **shape** of the change, not the
//     values — e.g. {"field":"openai_api_key","action":"set","hint":"sk-...XYZ"}.
//   - RequestID is the same id stamped onto the request's structured
//     log entries by the chi RequestID middleware (or generated by the
//     audit middleware itself when no upstream id exists). Lets an
//     operator join an audit row back to slog / future tracing output.
type Log struct {
	ID           uint64    `gorm:"primaryKey;autoIncrement"`
	OccurredAt   time.Time `gorm:"not null;index:idx_audit_occurred"`
	UserID       *uint64   `gorm:"index:idx_audit_user,priority:1"`
	UserEmail    string    `gorm:"size:255;not null"`
	Role         string    `gorm:"size:16;not null"`
	IP           string    `gorm:"size:45;not null"`
	UserAgent    string    `gorm:"size:512;not null"`
	Action       string    `gorm:"size:64;not null;index:idx_audit_action,priority:1"`
	ResourceType string    `gorm:"size:32;not null;index:idx_audit_resource,priority:1"`
	ResourceID   string    `gorm:"size:128;not null;index:idx_audit_resource,priority:2"`
	ResourceName string    `gorm:"size:256;not null"`
	Status       string    `gorm:"size:16;not null;index:idx_audit_status,priority:1"`
	ErrorCode    string    `gorm:"size:64;not null"`
	ErrorMessage string    `gorm:"size:512;not null"`
	PayloadJSON  string    `gorm:"type:text"`
	RequestID    string    `gorm:"size:64;not null"`
	CreatedAt    time.Time `gorm:"autoCreateTime"`

	// Chain columns. HLD-010's tamper-evidence lives here: Seq is the
	// row's position in the append-only chain, PrevHash is the Hash of
	// the row before it, and Hash is the keyed digest over both plus
	// every field above. Editing any field of any row invalidates that
	// row's Hash and therefore every Hash after it, so a deletion or an
	// edit cannot hide behind a later row that still looks plausible.
	//
	// Seq is 0 on rows written before the chain was switched on. Zero is
	// the "unchained" marker rather than a position, which is what lets
	// the chain be introduced on a live table without a backfill that
	// would have to invent a history nobody can verify anyway.
	Seq      uint64 `gorm:"not null;default:0;index:idx_audit_seq"`
	PrevHash string `gorm:"size:64;not null;default:''"`
	Hash     string `gorm:"size:64;not null;default:''"`
}

// ChainHead is the single row that serialises the hash chain.
//
// One row, id=1, holding the sequence number and hash of the most
// recently appended entry. It exists because a chain built from a
// cached in-process head forks the moment a second manager instance
// writes: both read the same head, both stamp the same PrevHash, and
// the result verifies as intact right up to the point where it is not.
// The head is instead advanced with a compare-and-swap on Seq inside
// the same transaction that inserts the entry, so a writer that lost
// the race fails its update, reads the new head, and retries — and a
// writer that crashes between the two leaves a head that is too high
// rather than an entry that chains to nothing.
type ChainHead struct {
	ID        uint64    `gorm:"primaryKey;autoIncrement:false"`
	Seq       uint64    `gorm:"not null;default:0"`
	Hash      string    `gorm:"size:64;not null;default:''"`
	UpdatedAt time.Time `gorm:"autoUpdateTime"`
}

// TableName pins the head table. The constant name is spelled out in
// code rather than left to GORM's pluraliser so a rename of the model
// cannot silently orphan every writer's head.
func (ChainHead) TableName() string { return "audit_chain_head" }

// ChainHeadID is the fixed primary key of the one head row. It is not
// an auto-increment sequence: there is exactly one head, and a second
// one would mean two chains.
const ChainHeadID uint64 = 1

// TableName pins the table so a package rename doesn't silently create a
// parallel empty table.
func (Log) TableName() string { return "audit_logs" }

// The action / resource / status vocabulary below was moved to
// core/base/pkg/audit in decision 109 and is re-exported here rather
// than duplicated. Two things depend on it being one definition: the
// middleware buckets an HTTP status into Status* before the writer ever
// sees the row, and iam's handlers name actions from another bounded
// context — which is exactly why the constants cannot live above them.
// A const alias is a compile-time identity, so a row written with
// auditmodel.ActionUserCreate and a row written with
// auditport.ActionUserCreate are the same string by construction, not by
// a test that would eventually be forgotten.
const (
	StatusSuccess = auditport.StatusSuccess
	StatusFailure = auditport.StatusFailure
	StatusDenied  = auditport.StatusDenied

	ActionAuthLoginFailed = auditport.ActionAuthLoginFailed

	ActionUserCreate = auditport.ActionUserCreate
	ActionUserUpdate = auditport.ActionUserUpdate
	ActionUserDelete = auditport.ActionUserDelete
	ActionUserExport = auditport.ActionUserExport

	ActionDeviceUpdate = auditport.ActionDeviceUpdate
	ActionDeviceDelete = auditport.ActionDeviceDelete

	ActionKnowledgeDocCreate = auditport.ActionKnowledgeDocCreate
	ActionKnowledgeDocUpload = auditport.ActionKnowledgeDocUpload
	ActionKnowledgeDocUpdate = auditport.ActionKnowledgeDocUpdate
	ActionKnowledgeDocMove   = auditport.ActionKnowledgeDocMove
	ActionKnowledgeDocDelete = auditport.ActionKnowledgeDocDelete

	ActionRuleCreate = auditport.ActionRuleCreate
	ActionRuleUpdate = auditport.ActionRuleUpdate
	ActionRuleDelete = auditport.ActionRuleDelete

	ActionIncidentAck     = auditport.ActionIncidentAck
	ActionIncidentResolve = auditport.ActionIncidentResolve
	ActionIncidentSilence = auditport.ActionIncidentSilence

	ActionSettingUpdate = auditport.ActionSettingUpdate
	ActionSettingDelete = auditport.ActionSettingDelete

	ActionSecretCreate = auditport.ActionSecretCreate
	ActionSecretUpdate = auditport.ActionSecretUpdate
	ActionSecretDelete = auditport.ActionSecretDelete

	ActionOrgCreate       = auditport.ActionOrgCreate
	ActionOrgUpdate       = auditport.ActionOrgUpdate
	ActionOrgDelete       = auditport.ActionOrgDelete
	ActionOrgMemberAdd    = auditport.ActionOrgMemberAdd
	ActionOrgMemberUpdate = auditport.ActionOrgMemberUpdate
	ActionOrgMemberRemove = auditport.ActionOrgMemberRemove

	ActionAgentSessionOpen  = auditport.ActionAgentSessionOpen
	ActionAgentMessageSend  = auditport.ActionAgentMessageSend
	ActionAgentSessionStop  = auditport.ActionAgentSessionStop
	ActionAgentSessionClose = auditport.ActionAgentSessionClose
	ActionAgentDecide       = auditport.ActionAgentDecide

	ActionRecoveryRetryIncrement = auditport.ActionRecoveryRetryIncrement
	ActionRecoveryRetryReset     = auditport.ActionRecoveryRetryReset

	ActionChatDiagnose = auditport.ActionChatDiagnose
	ActionChatPromote  = auditport.ActionChatPromote
	ActionChatReport   = auditport.ActionChatReport

	ActionPanelCreate = auditport.ActionPanelCreate
	ActionPanelUpdate = auditport.ActionPanelUpdate
	ActionPanelDelete = auditport.ActionPanelDelete

	ActionPageDelete = auditport.ActionPageDelete
	ActionPageShare  = auditport.ActionPageShare

	ActionGatewayLogin   = auditport.ActionGatewayLogin
	ActionConsumerCreate = auditport.ActionConsumerCreate
	ActionConsumerDelete = auditport.ActionConsumerDelete

	ActionChannelCreate = auditport.ActionChannelCreate
	ActionChannelUpdate = auditport.ActionChannelUpdate
	ActionChannelDelete = auditport.ActionChannelDelete

	ActionRepoCreate = auditport.ActionRepoCreate
	ActionRepoDelete = auditport.ActionRepoDelete
	ActionRepoSync   = auditport.ActionRepoSync

	ActionSkillInstall   = auditport.ActionSkillInstall
	ActionSkillUninstall = auditport.ActionSkillUninstall
	ActionSkillExecute   = auditport.ActionSkillExecute

	ActionPluginReleaseStart    = auditport.ActionPluginReleaseStart
	ActionPluginReleaseAdvance  = auditport.ActionPluginReleaseAdvance
	ActionPluginReleaseHalt     = auditport.ActionPluginReleaseHalt
	ActionPluginReleaseRollback = auditport.ActionPluginReleaseRollback

	ActionAutonomyExecute = auditport.ActionAutonomyExecute

	ActionAgentTeamsTokenIssue = auditport.ActionAgentTeamsTokenIssue

	// 决策 332：两条节点侧后果最重的控制面写路由——谁换了它的凭据、它上面跑什么插件。
	// 决策 334：节点生命周期两端——谁把它放进来、谁把它摘出去。
	ActionEdgeRotateSecret = auditport.ActionEdgeRotateSecret
	ActionEdgeRegister     = auditport.ActionEdgeRegister
	ActionEdgeDelete       = auditport.ActionEdgeDelete

	// 决策 335：编排面。flow_run 与 flow_test_node 是整个平台后果最重的两行——
	// 一份编排是一串工具调用，按一次就真的发生。
	ActionFlowCreate   = auditport.ActionFlowCreate
	ActionFlowGenerate = auditport.ActionFlowGenerate
	ActionFlowUpdate   = auditport.ActionFlowUpdate
	ActionFlowDelete   = auditport.ActionFlowDelete
	ActionFlowToggle   = auditport.ActionFlowToggle
	ActionFlowRun      = auditport.ActionFlowRun
	ActionFlowTestNode = auditport.ActionFlowTestNode

	// 决策 336：SSH 身份——一把能登上具名主机的私钥。generate 与 create 分开，
	// 因为只有 generate 是**平台自己铸**的，那把私钥此后再也不会出现。
	ActionSSHKeyRegister = auditport.ActionSSHKeyRegister
	ActionSSHKeyGenerate = auditport.ActionSSHKeyGenerate
	ActionSSHKeyUpdate   = auditport.ActionSSHKeyUpdate
	ActionSSHKeyDelete   = auditport.ActionSSHKeyDelete
	ActionEdgePluginSet  = auditport.ActionEdgePluginSet

	// 决策 337：报表面。share 是这一族里后果最重的一行——它铸出一个**无需认证**
	// 就能读到这份报表的 token，而链不能撤销它，所以这一行唯一不能包含的就是
	// 那个 token 本身。schedule_* 单独成族：一条 schedule 是一台没人盯着就会
	// 自己发报文的机器，enabled 与 cron_spec 决定它会做什么。
	ActionReportGenerate = auditport.ActionReportGenerate
	ActionReportShare    = auditport.ActionReportShare
	ActionReportDelete   = auditport.ActionReportDelete
	ActionScheduleCreate = auditport.ActionScheduleCreate
	ActionScheduleUpdate = auditport.ActionScheduleUpdate
	ActionScheduleDelete = auditport.ActionScheduleDelete
	ActionScheduleToggle = auditport.ActionScheduleToggle
	ActionScheduleRun    = auditport.ActionScheduleRun

	// 决策 338：一次性任务面与 schedule 是同一族的后门——发的是同一种报文，
	// 只是不由 cron 触发。前缀带 report_ 是为了不和将来的非报表任务抢 task_*。
	ActionReportTaskCreate = auditport.ActionReportTaskCreate
	ActionReportTaskRerun  = auditport.ActionReportTaskRerun
	ActionReportTaskDelete = auditport.ActionReportTaskDelete

	// 决策 339：拓扑面十个动作。与前面各族不同，这里改的不是一份产物，而是
	// **平台用来推理的那张图**——一条边决定关联查询能不能走到。
	ActionTopologyNodeCreate         = auditport.ActionTopologyNodeCreate
	ActionTopologyNodeUpdate         = auditport.ActionTopologyNodeUpdate
	ActionTopologyNodeDelete         = auditport.ActionTopologyNodeDelete
	ActionTopologyRelationCreate     = auditport.ActionTopologyRelationCreate
	ActionTopologyRelationUpdate     = auditport.ActionTopologyRelationUpdate
	ActionTopologyRelationDelete     = auditport.ActionTopologyRelationDelete
	ActionTopologyRelationTypeCreate = auditport.ActionTopologyRelationTypeCreate
	ActionTopologyRelationTypeDelete = auditport.ActionTopologyRelationTypeDelete
	ActionTopologyNodeTypeCreate     = auditport.ActionTopologyNodeTypeCreate
	ActionTopologyNodeTypeDelete     = auditport.ActionTopologyNodeTypeDelete

	// 决策 341：联邦面。这一族改的不是本平台的一个对象，而是**另一个集群将要
	// 执行什么**——一个版本签发下去，一台本仓库不直接管理的机器就换了它允许做的事。
	ActionFederationClusterEnroll   = auditport.ActionFederationClusterEnroll
	ActionFederationPolicyPublish   = auditport.ActionFederationPolicyPublish
	ActionFederationPolicyRedeliver = auditport.ActionFederationPolicyRedeliver
	ActionFederationPolicyAck       = auditport.ActionFederationPolicyAck

	// 决策 333：供应链面（谁把哪段字节推到了哪台机器上）与「谁掐掉了这个会话」。
	ActionEdgeAgentUpgrade    = auditport.ActionEdgeAgentUpgrade
	ActionEdgePackageUpgrade  = auditport.ActionEdgePackageUpgrade
	ActionWebshellSessionKill = auditport.ActionWebshellSessionKill

	ActionMCPToolCall      = auditport.ActionMCPToolCall
	ActionMCPToolAuthorize = auditport.ActionMCPToolAuthorize

	ActionNodeToolCall        = auditport.ActionNodeToolCall
	ActionNodeToolBlocked     = auditport.ActionNodeToolBlocked
	ActionNodeToolFailed      = auditport.ActionNodeToolFailed
	ActionNodeApprovalRequest = auditport.ActionNodeApprovalRequest
	ActionNodeApprovalGrant   = auditport.ActionNodeApprovalGrant
	ActionNodeApprovalDeny    = auditport.ActionNodeApprovalDeny
	ActionNodeAgentTurn       = auditport.ActionNodeAgentTurn
	ActionNodeModelCall       = auditport.ActionNodeModelCall
	ActionNodePluginInstall   = auditport.ActionNodePluginInstall
	ActionNodePluginRemove    = auditport.ActionNodePluginRemove
	ActionNodePluginLoad      = auditport.ActionNodePluginLoad
	ActionRetentionTruncate   = auditport.ActionRetentionTruncate
	ActionNodeProposalCreate  = auditport.ActionNodeProposalCreate
	ActionNodeRecoveryApply   = auditport.ActionNodeRecoveryApply

	ActionAgentToolCall = auditport.ActionAgentToolCall

	ActionCrystallizePromote = auditport.ActionCrystallizePromote
	ActionCrystallizeRelease = auditport.ActionCrystallizeRelease

	ActionApprovalApprove = auditport.ActionApprovalApprove
	ActionApprovalReject  = auditport.ActionApprovalReject

	ActionIncidentInvestigate = auditport.ActionIncidentInvestigate

	ActionIMAppCreate            = auditport.ActionIMAppCreate
	ActionIMAppUpdate            = auditport.ActionIMAppUpdate
	ActionIMAppDelete            = auditport.ActionIMAppDelete
	ActionHITLDecide             = auditport.ActionHITLDecide
	ActionDataGuardLabelSet      = auditport.ActionDataGuardLabelSet
	ActionDataGuardLabelOverride = auditport.ActionDataGuardLabelOverride
	ActionDataGuardLabelDelete   = auditport.ActionDataGuardLabelDelete
	ActionHITLProposalCreate     = auditport.ActionHITLProposalCreate
	ActionHITLProposalApprove    = auditport.ActionHITLProposalApprove
	ActionHITLProposalReject     = auditport.ActionHITLProposalReject
	ActionHITLProposalExpire     = auditport.ActionHITLProposalExpire

	ActionIMAppSecretReveal = auditport.ActionIMAppSecretReveal

	ResourceUser             = auditport.ResourceUser
	ResourceDevice           = auditport.ResourceDevice
	ResourceKnowledgeDoc     = auditport.ResourceKnowledgeDoc
	ResourceIncident         = auditport.ResourceIncident
	ResourceSetting          = auditport.ResourceSetting
	ResourceSecret           = auditport.ResourceSecret
	ResourceOrg              = auditport.ResourceOrg
	ResourceAgentSession     = auditport.ResourceAgentSession
	ResourceChatConversation = auditport.ResourceChatConversation
	ResourcePanel            = auditport.ResourcePanel
	ResourceHostedPage       = auditport.ResourceHostedPage
	ResourceGatewayConsumer  = auditport.ResourceGatewayConsumer
	ResourceRule             = auditport.ResourceRule
	ResourceChannel          = auditport.ResourceChannel
	ResourceRepo             = auditport.ResourceRepo
	ResourceSkill            = auditport.ResourceSkill
	ResourceLLM              = auditport.ResourceLLM
	ResourceGitKey           = auditport.ResourceGitKey
	ResourceGrafana          = auditport.ResourceGrafana
	ResourceRAG              = auditport.ResourceRAG
	ResourceAudit            = auditport.ResourceAudit
	ResourceAuth             = auditport.ResourceAuth
	ResourcePlugin           = auditport.ResourcePlugin
	ResourceEdge             = auditport.ResourceEdge
	ResourceAuditChain       = auditport.ResourceAuditChain
	ResourceApproval         = auditport.ResourceApproval
	ResourceIMApp            = auditport.ResourceIMApp
	ResourceAgentTeamsTask   = auditport.ResourceAgentTeamsTask
	ResourceDataGuardLabel   = auditport.ResourceDataGuardLabel
	ResourceHITLProposal     = auditport.ResourceHITLProposal
	ResourceWebshellSession  = auditport.ResourceWebshellSession
	ResourceFlow             = auditport.ResourceFlow
	ResourceMCPTool          = auditport.ResourceMCPTool

	ResourceAgentTool = auditport.ResourceAgentTool

	// 决策 337：report 与 report_schedule 是两个资源而不是一个——「凌晨三点会发什么」
	// 要看 schedule，「上周发过什么」要看 report，合成一个就变成载荷扫描。
	ResourceReport         = auditport.ResourceReport
	ResourceReportSchedule = auditport.ResourceReportSchedule
	ResourceReportTask     = auditport.ResourceReportTask

	// 决策 339：拓扑的四个资源。node_type 与 relation_type 分开是因为**删除的
	// 后果不在同一个量级**——删一个 node_type 只是图例少了一类，删一个
	// relation_type 会让它下面的每一条边失去语义。
	ResourceTopologyNode         = auditport.ResourceTopologyNode
	ResourceTopologyRelation     = auditport.ResourceTopologyRelation
	ResourceTopologyRelationType = auditport.ResourceTopologyRelationType
	ResourceTopologyNodeType     = auditport.ResourceTopologyNodeType

	// 决策 341：四条联邦路由共用一个资源——「哪个集群正在执行那个版本」是它们的
	// 第一个问题，而四条路由的路径里带的是同一个 cluster id。
	ResourceFederationCluster = auditport.ResourceFederationCluster

	// 决策 342：device 的动作有两个（device_update / device_delete）早就在词表里，
	// 本刀只加了 device_roles_set —— 它是全仓权限变更的唯一入口。
	ActionDeviceRolesSet = auditport.ActionDeviceRolesSet
)
