// Package chatdiagnose holds the persistence entity for the
// conversational-diagnosis spec (D14 of zero-manual-ops-loop).
//
// Schema philosophy: borrowed from v1 chat-conversation-persistence
// (DB 单一源 + rehydration) — NOT a copy. The conversation row is
// the fact source; in-memory caches in the biz layer are merely a
// performance hint, never the truth.
//
// Invariants enforced here:
//
//   - tenant_id is mandatory and indexed — every biz read/write MUST
//     scope by tenant. Cross-tenant access is rejected at the repo
//     layer (see biz/chatdiagnose.ConversationRepo.GetConversation).
//   - title is nullable in spirit (the LLM-generated title arrives
//     asynchronously after the first turn; the column is NOT NULL
//     at the DB layer but the biz layer may write an empty string
//     and patch it later).
//   - root_incident_id is nullable — exploratory chats (no incident
//     attached yet) co-exist with chats that were promoted from an
//     incident.
//   - metadata is JSONB (Postgres) / TEXT (MySQL via GORM Driver)
//     and is opaque to this package. Biz callers marshal/unmarshal.
//
// Append-only contract on Conversation is "soft" — title and
// updated_at MAY be updated after the first turn (the LLM-generated
// title is the canonical use case). All other columns are write-once.
package chatdiagnose

import "time"

// Conversation is one chat thread. The DB row is the single source of
// truth; the biz layer's in-memory cache is best-effort.
type Conversation struct {
	// ID is the primary key, generated by the biz layer (UUID v4 or
	// snowflake — see biz/chatdiagnose.generateID). 64 chars leaves
	// headroom for either scheme plus a tenant prefix in the future.
	ID string `json:"id" gorm:"primaryKey;size:64"`

	// TenantID enforces multi-tenant isolation. Indexed for the
	// "list my conversations" path AND for the "is this conversation
	// mine?" cross-tenant guard at conversation-resume time.
	TenantID string `json:"tenant_id" gorm:"index;size:64;not null"`

	// UserID is the owning user. Indexed for per-user listing and
	// for ownership checks at the audit layer.
	UserID string `json:"user_id" gorm:"index;size:64;not null"`

	// Title is the human-readable conversation name. Generated by the
	// LLM asynchronously after the first turn (Day 2 spike — the
	// chatruntime side will produce it). Initial value is the
	// truncated first user_message (see biz/chatdiagnose.getOrCreate
	// Conversation).
	Title string `json:"title" gorm:"size:256"`

	// RootIncidentID is the FK to the parent incident, nullable.
	// Exploratory chats (no incident) leave this NULL. Promoted chats
	// (chat -> loop) fill it when the user clicks "启动修复".
	RootIncidentID *string `json:"root_incident_id,omitempty" gorm:"index;size:64"`

	// Metadata is the free-form JSONB blob. Biz layer is responsible
	// for marshalling. Stored as text via gorm driver portability;
	// on Postgres the column type is JSONB at the migration layer.
	Metadata string `json:"metadata" gorm:"type:json"`

	// CreatedAt / UpdatedAt. Index on created_at for "recent chats"
	// list ordering.
	CreatedAt time.Time `json:"created_at" gorm:"index"`
	UpdatedAt time.Time `json:"updated_at"`

	// Append-only soft contract:
	//
	//   - Title and UpdatedAt MAY be updated after the first turn
	//     (LLM-generated title arrives async).
	//   - All other columns (ID, TenantID, UserID, RootIncidentID,
	//     Metadata, CreatedAt) MUST be treated as write-once.
	//     Biz layer MUST NOT issue UPDATE statements that touch them
	//     after the initial INSERT.
	//
	// This invariant is enforced by convention + repo-layer guards,
	// not by GORM hooks. The chatdiagnose.ConversationRepo.Update
	// method only accepts (Title, UpdatedAt) — see biz layer.
}

// TableName pins the SQL table name.
func (Conversation) TableName() string { return "diagnostic_conversation" }
