// Command opskeeper-mcp-tools 调试工具：列 opskeeper MCP 工具、调用工具、导出 manifest。
//
// 用法：
//   opskeeper-mcp-tools list                     — 列出 /v1/mcp 工具（需 Bearer GWKey）
//   opskeeper-mcp-tools call <tool> --args '{...}' — 调用工具
//   opskeeper-mcp-tools manifest                — 导出 MCP server manifest (类似 mcp-github.yaml)
//   opskeeper-mcp-tools state get <task_id>     — 读 state.json
//   opskeeper-mcp-tools state put <task_id> <json> — 写 state.json
//
// 环境变量：
//   OPSKEEPER_BACKEND_URL   opskeeper base URL (default http://localhost:8443)
//   OPSKEEPER_GATEWAY_KEY   Bearer token (required for /v1/mcp)
//   OPSKEEPER_TENANT_ID     tenant_id (default "default")

package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "opskeeper-mcp-tools: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	switch args[0] {
	case "list":
		return cmdList()
	case "call":
		return cmdCall(args[1:])
	case "manifest":
		return cmdManifest()
	case "state":
		return cmdState(args[1:])
	case "help", "--help", "-h":
		usage()
		return nil
	default:
		usage()
		return fmt.Errorf("unknown action %q", args[0])
	}
}

func cmdList() error {
	body := jsonRPC("tools/list", nil)
	resp, err := postMCP("/v1/mcp", body)
	if err != nil {
		return err
	}
	result, _ := resp["result"].(map[string]any)
	tools, _ := result["tools"].([]any)
	fmt.Printf("%-30s %s\n", "NAME", "DESCRIPTION")
	fmt.Println(strings.Repeat("-", 80))
	for _, t := range tools {
		tool, _ := t.(map[string]any)
		name, _ := tool["name"].(string)
		desc, _ := tool["description"].(string)
		fmt.Printf("%-30s %s\n", name, truncate(desc, 80))
	}
	return nil
}

func cmdCall(args []string) error {
	fs := flag.NewFlagSet("call", flag.ContinueOnError)
	argsJSON := fs.String("args", "{}", "tool arguments as JSON string")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if fs.NArg() < 1 {
		return fmt.Errorf("call: missing tool name")
	}
	toolName := fs.Arg(0)
	var arguments any
	if err := json.Unmarshal([]byte(*argsJSON), &arguments); err != nil {
		return fmt.Errorf("call: invalid --args JSON: %w", err)
	}
	body := jsonRPC("tools/call", map[string]any{
		"name":      toolName,
		"arguments": arguments,
	})
	resp, err := postMCP("/v1/mcp", body)
	if err != nil {
		return err
	}
	out, _ := json.MarshalIndent(resp, "", "  ")
	fmt.Println(string(out))
	return nil
}

func cmdManifest() error {
	fmt.Println("# opskeeper MCP server manifest (generated by opskeeper-mcp-tools manifest)")
	fmt.Println("# Use with AgentTeams setup-mcp-server.sh via mcp-opskeeper.yaml.template pattern.")
	fmt.Println()
	fmt.Println("server:")
	fmt.Println("  name: opskeeper-mcp-server")
	fmt.Println("  config:")
	fmt.Println("    accessToken: \"\"   # substituted by setup script")
	fmt.Println()
	fmt.Println("# Tools (full list):")
	body := jsonRPC("tools/list", nil)
	resp, err := postMCP("/v1/mcp", body)
	if err != nil {
		return err
	}
	result, _ := resp["result"].(map[string]any)
	tools, _ := result["tools"].([]any)
	for _, t := range tools {
		tool, _ := t.(map[string]any)
		name, _ := tool["name"].(string)
		desc, _ := tool["description"].(string)
		schema, _ := tool["inputSchema"].(map[string]any)
		fmt.Println()
		fmt.Printf("- name: %s\n", name)
		fmt.Printf("  description: %q\n", desc)
		fmt.Println("  requestTemplate:")
		fmt.Printf("    url: %q\n", "${OPSKEEPER_BACKEND_URL}/v1/mcp")
		fmt.Println("    method: POST")
		fmt.Println("    body: |")
		fmt.Printf("      {\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":%q,\"arguments\":{}}}\n", name)
		fmt.Println("    headers:")
		fmt.Println("    - key: Authorization")
		fmt.Println("      value: \"Bearer {{.config.accessToken}}\"")
		fmt.Println("    - key: X-Opskeeper-Version")
		fmt.Println("      value: \"v1\"")
		if schema != nil {
			fmt.Println("  inputSchema:")
			schBytes, _ := json.MarshalIndent(schema, "    ", "  ")
			fmt.Println("    " + string(schBytes))
		}
	}
	return nil
}

func cmdState(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("state: need get/put subcommand")
	}
	switch args[0] {
	case "get":
		if len(args) < 2 {
			return fmt.Errorf("state get: need task_id")
		}
		return stateGet(args[1])
	case "put":
		if len(args) < 3 {
			return fmt.Errorf("state put: need task_id and JSON body")
		}
		return statePut(args[1], args[2])
	}
	return fmt.Errorf("state: unknown subcommand %q", args[0])
}

func stateGet(taskID string) error {
	url := backendURL() + "/v1/state/" + taskID
	req, _ := http.NewRequest(http.MethodGet, url, nil)
	applyAuth(req)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	fmt.Println(string(body))
	return nil
}

func statePut(taskID, jsonBody string) error {
	url := backendURL() + "/v1/state/" + taskID
	req, _ := http.NewRequest(http.MethodPut, url, strings.NewReader(jsonBody))
	applyAuth(req)
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	fmt.Println(string(body))
	return nil
}

// ---- helpers ----

func backendURL() string {
	if u := os.Getenv("OPSKEEPER_BACKEND_URL"); u != "" {
		return strings.TrimRight(u, "/")
	}
	return "http://localhost:8443"
}

func applyAuth(req *http.Request) {
	if key := os.Getenv("OPSKEEPER_GATEWAY_KEY"); key != "" {
		req.Header.Set("Authorization", "Bearer "+key)
	}
	if t := os.Getenv("OPSKEEPER_TENANT_ID"); t != "" {
		req.Header.Set("X-Opskeeper-Tenant", t)
	}
}

func jsonRPC(method string, params any) []byte {
	body, _ := json.Marshal(map[string]any{
		"jsonrpc": "2.0",
		"id":      1,
		"method":  method,
		"params":  params,
	})
	return body
}

func postMCP(path string, body []byte) (map[string]any, error) {
	url := backendURL() + path
	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	applyAuth(req)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Opskeeper-Version", "v1")
	httpClient := &http.Client{Timeout: 30 * time.Second}
	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("http: %w", err)
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode/100 != 2 {
		return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(raw))
	}
	var out map[string]any
	if err := json.Unmarshal(raw, &out); err != nil {
		return nil, fmt.Errorf("unmarshal: %w (raw: %s)", err, string(raw))
	}
	return out, nil
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-3] + "..."
}

func usage() {
	fmt.Print(`opskeeper-mcp-tools — debug CLI for opskeeper /v1/mcp

Usage:
  opskeeper-mcp-tools list                                — list tools
  opskeeper-mcp-tools call <tool> --args '{"k":"v"}'      — call tool
  opskeeper-mcp-tools manifest                            — export manifest YAML
  opskeeper-mcp-tools state get <task_id>                 — read state.json
  opskeeper-mcp-tools state put <task_id> <json>          — write state.json

Env:
  OPSKEEPER_BACKEND_URL   backend URL (default http://localhost:8443)
  OPSKEEPER_GATEWAY_KEY   Bearer token
  OPSKEEPER_TENANT_ID     tenant (default "default")
`)
}
