// opskeeper-gate, as the agent runtime builds it on a node.
//
// GENERATED by scripts/sync-pig-ops.sh from core/pig/extensions/opskeeper-gate.
// Do not edit: the next run overwrites this file, and
// TestEveryPackagedExtensionMatchesItsCanonicalSource fails if it drifts.
//
// The copy is deliberate. The agent builds extensions from source on
// the node it runs on, and a node has no access to an unpublished
// OpsKeeper module. A package that referenced the canonical path
// would install and then fail to build, which is the worst time to
// find out. So the wire vocabulary travels inside the extension as a
// local ./wire package, and the only remaining requirement is the PiG
// extension SDK, which the agent stages from its own tree.
module github.com/vincent-wuhan/opskeeper/plugins/pig-ops/opskeeper-sre-autonomy/extensions/opskeeper-gate

go 1.26.0

require github.com/MichaelKinsy/PiG/extensions/sdk v0.4.0
